### ISSUE TITLE
The position CSS Attribute

### ISSUE THREAD

**Issue by drodata** [drodata/blog#20]
## Positioned Element
1. _**positioned element**_: 计算过(Computed value)的属性值是：`relative`,
   `absolute` 或`fixed`;
2. _**absolutely positioned element**_: 包括`absoluted` 或`fixed`两种情况；
## 语法

``` css
position: static; /* default value */
position: relative;
position: absolute; 
position: fixed; 
```
## 解释

文档正常的显示顺序是自上而下的，例如下面三个 DIV:

``` html
<div id="a" class="block bg-danger"></div>
<div id="b" class="block bg-warning"></div>
<div id="c" class="block bg-success"></div>
```

应用如下简单样式：

``` css
.block {
    width: 100px;
    height: 100px;
}
```

显示如下：
![](https://drodata.files.wordpress.com/2016/03/position-static.png)
### `relative` 的含义

现在我们将 `#b` 添加如下样式：

``` css
#b {
    position:relative;
    left: 100px;
}
```

显示效果如下：
![](https://drodata.files.wordpress.com/2016/03/relative.png)
从中我们可以直观地看到`relative`的作用：
1. Div b 原来的位置还在（Div c 没有上移填补空缺）；
2. 在 Div b 原有位置的基础上，通过`left`, `right`, `top` 和`bottom` 进行相对偏移
### `absolute` 的含义

我们将上面 #b 的样式保持不变，仅仅将`position`值由`relative`改成`absolute`:

``` css
#b {
    position:absolute;
    left: 100px;
}
```

显示效果如下：
![](https://drodata.files.wordpress.com/2016/03/position-absolute.png)
通过对比，可以直观地看到`relative`与`absolute`的不同：
1. Div b 原来的地方没有了（Div c）上移填补其位；
2. Dib b 的偏移参考坐标变了：由原来的自己改为页面的左上角；
### `relative` 和 `absolute` 的区别
1. relative 保留元素原有的位置（Gap），absolute 则不保留；
2. 参考坐标不同：relative 偏移时的参考坐标是元素原来位置的左上角；absolute 偏移是参考的坐标是距离元素最近的、设置 position 属性的父元素（_nearest positioned ancestor_），如果没有这样的父元素（上面的例子就属这种情况），则参考对象是页面的左上角；

下面再看下 position 值为`absolute`的元素在有'_nearest positioned ancestor_' 的情况下的偏移效果。HTML 如下：

``` html
<div id="a" class="block bg-danger"></div>
<div id="b" class="block bg-warning">
    <div id="d" class="block bg-info"></div>
</div>
<div id="c" class="block bg-success"></div>
```

``` css
.block {
    width: 100px;
    height: 100px;
}
#b {
    position:relative;
    left: 100px;
}
#d {
    position:absolute;
    left: 50px;
    top: 50px;
}
```

输出：

![](https://drodata.files.wordpress.com/2016/03/position-absolute-nearest-positiined-ancestor.png)
### `fixed`

这个可根据字面意思帮助理解，顾名思义，fixed positioned elements 是“固定”的，这里的“固定”特指元素不会随着页面的滚动而滚动；另外，和 absolute positioned elements 类似，fixed positioned elements 也不会在页面中预留位置。
### `top`, `bottom`, 'left`,`right` 的参考坐标

以`left`为例：

> For absolutely positioned elements (those with `position: absolute` or `position: fixed`), it specifies **the distance between the _left margin edge of the element_ and *the left edge of its containing block***.
### 参考
- [MDN position](https://developer.mozilla.org/en-US/docs/Web/CSS/position)
- [right](https://developer.mozilla.org/en-US/docs/Web/CSS/right)
