### ISSUE TITLE
Flex

### ISSUE THREAD

**Issue by drodata** [drodata/blog#82]
```css
.weui-flex__item {
    -webkit-box-flex: 1;
    -webkit-flex: 1;
    /* flex: 1; */
}

.weui-flex {
    display: -webkit-box;
    display: -webkit-flex;
    display: flex;
}
```
